<section>
    <div class="row">
        <div class="col-md-12">
            <h3>SENHAS</h3>
        </div>
    </div>    
    <div class="row">
        <div class="col-md-12 text-right">
            <a href="<?php echo $this->url(array(
                'controller' => 'senha',
                'action' => 'add'
            ), null, true); ?>" class="btn btn-success">Nova Senha</a>
            <hr />
        </div>
    </div>
    <?php if ($this->senhas->count() > 0) : ?>
    <div class="row">
        <div class="col-md-6">
            <label><?php echo $this->senhas->count(); ?> Registros</label>            
        </div>
        <div class="col-md-6">
            <form class="form-inline">
                <div class="form-group">
                    <label class="sr-only" for="exampleInputAmount">Amount (in dollars)</label>
                    <div class="input-group">                            
                        <input type="text" class="form-control" id="exampleInputAmount" placeholder="Pesquisar...">
                        <div class="input-group-addon"><i class="glyphicon glyphicon-search"></i></div>
                    </div>
                </div>
            </form><br />
        </div>        
    </div>
    <div class="row">        
        <div class="col-md-12">            
            <div class="table-responsive">
                <table class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th class="col-md-3">Cliente</th>
                            <th class="col-md-2">Tipo</th>
                            <th>Host</th>
                            <th>Usuário</th>
                            <th>Senha</th>
                            <th class="col-md-1">Ações</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->senhas as $senha) : ?>
                        <tr>
                            <td><?php echo $senha->cliente_nome; ?></td>
                            <td><?php echo $senha->senha_tipo_nome; ?></td>
                            <td><?php echo $senha->senha_host; ?></td>
                            <td><?php echo $senha->senha_usuario; ?></td>
                            <td><?php echo $senha->senha_senha; ?></td>
                            <td class="text-center">
                                <a href="<?php echo $this->url(array(
                                    'controller' => 'senha',
                                    'action' => 'edit',
                                    'senha_id' => $senha->senha_id
                                ), null, true); ?>" class="text-warning"><i class="glyphicon glyphicon-edit"></i></a>
                                <a href="<?php echo $this->url(array(
                                    'controller' => 'senha',
                                    'action' => 'delete',
                                    'senha_id' => $senha->senha_id
                                ), null, true); ?>" class="text-danger"><i class="glyphicon glyphicon-trash"></i></a>
                                <!--<a href="" class="text-info"><i class="glyphicon glyphicon-search"></i></a>-->
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <?php endif; ?>
</section>
