<section>
    <div class="row">        
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <div class="well">
                <div class="text-center text-danger">
                    <h3>
                        <i class="glyphicon glyphicon-warning-sign"></i> 
                        <span> ÁREA RESTRITA <span>
                        <i class="glyphicon glyphicon-warning-sign"></i>
                    </h3>
                    <hr style="border-color: #DCDCDC;"/>
                </div>
                <?php echo $this->form; ?>
            </div>
        </div>
        <div class="col-md-4"></div>
    </div>
</section>
